---
# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

palettes:
  template: catppuccin-mocha
  list:
    catppuccin-mocha:
      rosewater: "#f5e0dc"
      flamingo: "#f2cdcd"
      pink: "#f5c2e7"
      mauve: "#cba6f7"
      red: "#f38ba8"
      maroon: "#eba0ac"
      peach: "#fab387"
      yellow: "#f9e2af"
      green: "#a6e3a1"
      teal: "#94e2d5"
      sky: "#89dceb"
      sapphire: "#74c7ec"
      blue: "#89b4fa"
      lavender: "#b4befe"
      text: "#cdd6f4"
      subtext1: "#bac2de"
      subtext0: "#a6adc8"
      overlay2: "#9399b2"
      overlay1: "#7f849c"
      overlay0: "#6c7086"
      surface2: "#585b70"
      surface1: "#45475a"
      surface0: "#313244"
      base: "#1e1e2e"
      mantle: "#181825"
      crust: "#11111b"
    catppuccin-macchiato:
      rosewater: "#f4dbd6"
      flamingo: "#f0c6c6"
      pink: "#f5bde6"
      mauve: "#c6a0f6"
      red: "#ed8796"
      maroon: "#ee99a0"
      peach: "#f5a97f"
      yellow: "#eed49f"
      green: "#a6da95"
      teal: "#8bd5ca"
      sky: "#91d7e3"
      sapphire: "#7dc4e4"
      blue: "#8aadf4"
      lavender: "#b7bdf8"
      text: "#cad3f5"
      subtext1: "#b8c0e0"
      subtext0: "#a5adcb"
      overlay2: "#939ab7"
      overlay1: "#8087a2"
      overlay0: "#6e738d"
      surface2: "#5b6078"
      surface1: "#494d64"
      surface0: "#363a4f"
      base: "#24273a"
      mantle: "#1e2030"
      crust: "#181926"
    catppuccin-frappe:
      rosewater: "#f2d5cf"
      flamingo: "#eebebe"
      pink: "#f4b8e4"
      mauve: "#ca9ee6"
      red: "#e78284"
      maroon: "#ea999c"
      peach: "#ef9f76"
      yellow: "#e5c890"
      green: "#a6d189"
      teal: "#81c8be"
      sky: "#99d1db"
      sapphire: "#85c1dc"
      blue: "#8caaee"
      lavender: "#babbf1"
      text: "#c6d0f5"
      subtext1: "#b5bfe2"
      subtext0: "#a5adce"
      overlay2: "#949cbb"
      overlay1: "#838ba7"
      overlay0: "#737994"
      surface2: "#626880"
      surface1: "#51576d"
      surface0: "#414559"
      base: "#303446"
      mantle: "#292c3c"
      crust: "#232634"

palette:
  status-fg-success: "#5faf00"
  status-fg-error: "#FF5252"

common:
  element: &element
    style: plain
    background: p:surface0
  project: &project
    <<: *element
    foreground: p:sky

blocks:
  - alignment: left
    segments:
      - foreground: p:text
        <<: *element
        template: " {{ if .WSL }}WSL at {{ end }}{{.Icon}} ÓÇ±"
        type: os
      - foreground: p:red
        <<: *element
        template: " ÔÉß <#bac2de>ÓÇ±</>"
        type: root
        comment: Show when the current user is root or when in an elevated shell (Windows)
      - foreground: p:sapphire
        <<: *element
        properties:
          style: full
          edge_format: "<b>%s</b>"
          max_width: 80
        template: " ÔÅº {{ .Path }} "
        type: path
      - foreground: p:green
        <<: *element
        templates:
          - "<#bac2de>ÓÇ±</> {{ .HEAD }}"
          - "{{ if .BranchStatus }} {{ .BranchStatus }} {{ end }}"
          - "{{ if .Staging.Changed }}ÓÇ± Ó©† {{ .Staging.String }} {{ end }}"
          - "{{ if .Working.Changed }}ÓÇ± ÔÅÄ {{ .Working.String }} {{ end }}"
          - "{{ if gt .StashCount 0 }}ÓÇ± ÔÉá {{ .StashCount }} {{ end }}"
        properties:
          branch_max_length: 0
          branch_icon: "ÔÑ¶ "
          branch_identical_icon: "ÔëÑ"
          branch_gone_icon: "Ó™∏"
          branch_behind_icon: "ÔÅ£"
          branch_ahead_icon: "ÔÅ¢"
          fetch_stash_count: true
          fetch_status: true
          fetch_upstream_icon: true
          mapped_branches:
            feature/*: "üöÄ "
            feat/*: "üöÄ "
            work/*: "üî® "
          tag_icon: "Ôêí "
          rebase_icon: "Óú® "
          git_icon: "Óóª "
          merge_icon: "Óúß "
          commit_icon: "Ôêó "
          revert_icon: "ÔÉ¢ "
          no_commits_icon: "Ôñî "
          cherry_pick_icon: "Óäõ "
          full_branch_path: true
        type: git
      - background: transparent
        foreground: p:surface0
        style: plain
        template: "ÓÇ∞"
        type: text
    type: prompt
  - alignment: right
    filler: "<#313244,transparent>¬∑</>"
    segments:
      - foreground: p:surface0
        background: transparent
        style: plain
        template: "ÓÇ≤"
        type: text
      - foreground: p:green
        <<: *element
        foreground_templates:
          - "{{ if .Error }}p:red{{ end }}"
        templates:
          - "{{ if .Error }}{{ .String }}ÔÄç {{ end }}"
          - "<#bac2de>ÓÇ≥</>"
        properties:
          status_template: " {{ reason .Code }} "
        type: status
      - foreground: p:subtext0
        <<: *element
        type: executiontime
        templates:
          - " {{ .FormattedMs }}"
          - " Û±¶ü"
          - " <#bac2de>ÓÇ≥</>"
        properties:
          threshold: 500
          style: austin
      - type: text
        <<: *element
        foreground: p:yellow
        template: "{{ if .Env.DIRENV_FILE }} ÔÄì <#bac2de>ÓÇ≥</>{{ end }}"
      - type: project
        <<: *project
        templates:
          - " {{ if .Error }}{{ .Error }}{{ else }}{{ if .Name }}{{ .Name }}{{ end }} {{ if .Version }}{{.Version}} Ôíá{{ end }}{{ end }}"
          - " <#bac2de>ÓÇ≥</>"
      - type: cmake
        <<: *project
        templates:
          - " {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
          - " Óòû Óòù"
          - " <#bac2de>ÓÇ≥</>"
      - type: python
        <<: *project
        templates:
          - " {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}"
          - " Óàµ"
          - " <#bac2de>ÓÇ≥</>"
      - type: rust
        <<: *project
        templates:
          - " {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
          - " Óû®"
          - " <#bac2de>ÓÇ≥</>"
      - type: lua
        <<: *project
        templates:
          - " {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
          - " Óò†"
          - " <#bac2de>ÓÇ≥</>"
      - type: perl
        <<: *project
        templates:
          - " {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
          - " Óôæ"
          - " <#bac2de>ÓÇ≥</>"
      - type: go
        <<: *project
        templates:
          - " {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
          - " Óòß"
          - " <#bac2de>ÓÇ≥</>"
      - foreground: p:yellow
        <<: *element
        templates:
          - " {{ .UserName }}@{{ .HostName }}"
          - " {{ if .SSHSession }}ÓÆ©{{ else }}ÔÄá{{ end }}"
          - " <#bac2de>ÓÇ≥</>"
        type: session
      - foreground: p:subtext1
        <<: *element
        properties:
          time_format: "15:04:05"
        template: " {{ .CurrentDate | date .Format }} ÔÄó "
        type: time
    type: prompt
    overflow: hide
  - alignment: left
    newline: true
    segments:
      - foreground: p:status-fg-success
        foreground_templates:
          - "{{ if .Error }}p:status-fg-error{{ end }}"
        background: transparent
        properties:
          always_enabled: true
        style: plain
        template: "‚ùØ "
        type: status
    type: prompt
version: 2
